
#define TASK_DELAY_DEF 20
#define TASK_DELAY_FAST 5

#define TASK_PRIO_DEF 1
#define TASK_STACK_DEF 600
#define TASK_PARAMS_DEF NULL
#define TASK_HANDLER_DEF NULL

#define QUEUE_DEF_SIZE 30

#define TASK_DEFS TASK_STACK_DEF, TASK_PARAMS_DEF, TASK_PRIO_DEF, TASK_HANDLER_DEF
